// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdoEc1L7wT7LNn0Z3g0rcDHri3l3LMguE',
    appId: '1:223137455700:web:1c4fd5900b2ff7382317c1',
    messagingSenderId: '223137455700',
    projectId: 'uberclonerider-5105a',
    authDomain: 'uberclonerider-5105a.firebaseapp.com',
    databaseURL: 'https://uberclonerider-5105a-default-rtdb.firebaseio.com',
    storageBucket: 'uberclonerider-5105a.firebasestorage.app',
    measurementId: 'G-P5C282XHLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEjuN1ZjXaToNRXWLzl88DAj3EV1ddsI0',
    appId: '1:223137455700:android:3f91bfdf6ee6addd2317c1',
    messagingSenderId: '223137455700',
    projectId: 'uberclonerider-5105a',
    databaseURL: 'https://uberclonerider-5105a-default-rtdb.firebaseio.com',
    storageBucket: 'uberclonerider-5105a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHzjdQ7dHszMF_ymHe4n7fjZ3I791lwsg',
    appId: '1:223137455700:ios:b04d389df89b84cb2317c1',
    messagingSenderId: '223137455700',
    projectId: 'uberclonerider-5105a',
    databaseURL: 'https://uberclonerider-5105a-default-rtdb.firebaseio.com',
    storageBucket: 'uberclonerider-5105a.firebasestorage.app',
    iosClientId: '223137455700-l9edo7curddcj42lojv2ips7omt39a6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.uber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHzjdQ7dHszMF_ymHe4n7fjZ3I791lwsg',
    appId: '1:223137455700:ios:b04d389df89b84cb2317c1',
    messagingSenderId: '223137455700',
    projectId: 'uberclonerider-5105a',
    databaseURL: 'https://uberclonerider-5105a-default-rtdb.firebaseio.com',
    storageBucket: 'uberclonerider-5105a.firebasestorage.app',
    iosClientId: '223137455700-l9edo7curddcj42lojv2ips7omt39a6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.uber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdoEc1L7wT7LNn0Z3g0rcDHri3l3LMguE',
    appId: '1:223137455700:web:470a510d9205b51d2317c1',
    messagingSenderId: '223137455700',
    projectId: 'uberclonerider-5105a',
    authDomain: 'uberclonerider-5105a.firebaseapp.com',
    databaseURL: 'https://uberclonerider-5105a-default-rtdb.firebaseio.com',
    storageBucket: 'uberclonerider-5105a.firebasestorage.app',
    measurementId: 'G-JSBEN6LWMX',
  );
}
